### ISSUE TITLE
Website isn't very nice

### ISSUE THREAD

**Issue by Monkeyboy2805** [LolexOrg/Lolex-Tools#8]
@AvatarAing3 Your job 🎅 🎁

**Comment by AvatarAing3** [comment]
what is my job

**Comment by AvatarAing3** [comment]
i can't open anything

**Comment by AvatarAing3** [comment]
found the website project . working on it

**Comment by AvatarAing3** [comment]
@Monkeyboy2805  do i write in code ? never worked on this

**Comment by Monkeyboy2805** [comment]
@AvatarAing3 Yes, you do.

**Comment by Monkeyboy2805** [comment]
Sorry, btw I just didn't get round to responding.

**Comment by Monkeyboy2805** [comment]
Too busy updating for Python 3.6, came out on the 23rd 🤦‍♂️

**Comment by Monkeyboy2805** [comment]
@AvatarAing3 Make a PR once your done

**Comment by Monkeyboy2805** [comment]
@AvatarAing3 gitter.im/Lolex-Tools/Lobby is still open btw

**Comment by Monkeyboy2805** [comment]
@AvatarAing3 @lolget420ed Come on Gitter

**Comment by Monkeyboy2805** [comment]
ISSUE RESOLVED

**Comment by Monkeyboy2805** [comment]
@AvatarAing3 Come on Gitter, I need to ask you a few things
